version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: flextool_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - '5555:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  api:
    stdin_open: true
    build:
      context: ./backend2
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - postgres
    env_file:
      - ./backend2/.env
    ports:
      - '5000:5000'
    restart: always

  ui:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ui
    depends_on:
      - api
    env_file:
      - ./frontend/.env
    ports:
      - '3000:3000'
    restart: always

volumes:
  postgres-data:
  pgadmin-data:
